### ISSUE TITLE
Exception Running Contextual outlier detection using KDE/TreeKDE/BinnedKDE 

### ISSUE THREAD

**Issue by raininthesun** [stanford-futuredata/macrobase#135]
@mamikonyana 

`Exception in thread "main" org.apache.commons.math3.exception.MathUnsupportedOperationException: unsupported operation
    at org.apache.commons.math3.linear.EigenDecomposition.getSquareRoot(EigenDecomposition.java:382)
    at macrobase.analysis.stats.KDE.calculateBandwidthAncillaries(KDE.java:152)
    at macrobase.analysis.stats.KDE.setBandwidth(KDE.java:91)
    at macrobase.analysis.stats.KDE.setBandwidth(KDE.java:139)
    at macrobase.analysis.stats.KDE.train(KDE.java:158)
    at macrobase.analysis.transform.BatchScoreFeatureTransform.consume(BatchScoreFeatureTransform.java:38)
    at macrobase.analysis.contextualoutlier.ContextualOutlierDetector.contextualOutlierDetection(ContextualOutlierDetector.java:437)
    at macrobase.analysis.contextualoutlier.ContextualOutlierDetector.searchContextualOutliers(ContextualOutlierDetector.java:129)
    at macrobase.analysis.pipeline.BasicContextualBatchedPipeline.run(BasicContextualBatchedPipeline.java:55)
    at macrobase.runtime.command.MacroBasePipelineCommand.run(MacroBasePipelineCommand.java:37)
    at macrobase.runtime.command.MacroBasePipelineCommand.run(MacroBasePipelineCommand.java:17)
    at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:77)
    at io.dropwizard.cli.Cli.run(Cli.java:70)
    at io.dropwizard.Application.run(Application.java:80)
    at macrobase.runtime.MacroBaseServer.main(MacroBaseServer.java:20)
    at macrobase.MacroBase.main(MacroBase.java:33)`

**Comment by pbailis** [comment]
@mamikonyana: any thoughts on this?

**Comment by mamikonyana** [comment]
I suspect this is because we end up with a singular matrix at some point.
I'm not how much Edward is changing this and if it's worth investigating before he makes his changes.
I've suggested Xu to use other density estimators that I'm currently working on, which I'll try to address his issues in more reasonable time frame

**Comment by edgan8** [comment]
I've changed the KDE estimators to avoid using matrices for performance reasons (I don't think it's worth investing in non-diagonal covariance matrices), so this won't be an issue once the new kde stuff lands

**Comment by pbailis** [comment]
#180 should kill this
