### ISSUE TITLE
Exception when using EM_GMM for contextual outlier detection

### ISSUE THREAD

**Issue by raininthesun** [stanford-futuredata/macrobase#137]
@mamikonyana 

`Exception in thread "main" org.apache.commons.math3.linear.SingularMatrixException: matrix is singular
    at org.apache.commons.math3.linear.EigenDecomposition$Solver.getInverse(EigenDecomposition.java:553)
    at org.apache.commons.math3.distribution.MultivariateNormalDistribution.<init>(MultivariateNormalDistribution.java:131)
    at org.apache.commons.math3.distribution.MultivariateNormalDistribution.<init>(MultivariateNormalDistribution.java:82)
    at macrobase.analysis.stats.distribution.MultivariateNormal.<init>(MultivariateNormal.java:18)
    at macrobase.analysis.stats.mixture.ExpectMaxGMM.trainEM(ExpectMaxGMM.java:97)
    at macrobase.analysis.stats.mixture.ExpectMaxGMM.train(ExpectMaxGMM.java:33)
    at macrobase.analysis.transform.BatchScoreFeatureTransform.consume(BatchScoreFeatureTransform.java:37)
    at macrobase.analysis.contextualoutlier.ContextualOutlierDetector.contextualOutlierDetection(ContextualOutlierDetector.java:436)
    at macrobase.analysis.contextualoutlier.ContextualOutlierDetector.searchContextualOutliers(ContextualOutlierDetector.java:128)
    at macrobase.analysis.pipeline.BasicContextualBatchedPipeline.run(BasicContextualBatchedPipeline.java:58)
    at macrobase.runtime.command.MacroBasePipelineCommand.run(MacroBasePipelineCommand.java:37)
    at macrobase.runtime.command.MacroBasePipelineCommand.run(MacroBasePipelineCommand.java:17)
    at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:77)
    at io.dropwizard.cli.Cli.run(Cli.java:70)
    at io.dropwizard.Application.run(Application.java:80)
    at macrobase.runtime.MacroBaseServer.main(MacroBaseServer.java:20)
    at macrobase.MacroBase.main(MacroBase.java:33)`

**Comment by mamikonyana** [comment]
@raininthesun could you paste the command you ran?

Also I'd prefer that you use MEAN_FIELD_GMM, or SVI_GMM if your data size is 100k+

**Comment by raininthesun** [comment]
@mamikonyana 

Noted. This is a small dataset marketing. You may switch to branch `contextrank`, and run bin/batch.sh. You need to change `macrobase.loader.db.user` in conf/batch.yaml.

**Comment by pbailis** [comment]
@mamikonyana: any updates?

**Comment by mamikonyana** [comment]
Not yet, I'll look into it more.

**Comment by sweatybridge** [comment]
@raininthesun this stack trace no longer reflects the latest master, an update would be nice. 😄

**Comment by raininthesun** [comment]
@sweatybridge Indeed. I am swamped till Dec 1 due to a paper deadline and other things. I will make time for this after that if this is not blocking anybody.

**Comment by pbailis** [comment]
#180 should kill this
