### ISSUE TITLE
NullPointerException on cmtDatasetComplexStreaming sometimes

### ISSUE THREAD

**Issue by deepakn94** [stanford-futuredata/macrobase#17]
```
Exception in thread "main" java.lang.NullPointerException
	at macrobase.analysis.summary.itemset.StreamingFPGrowth$StreamingFPTree.sortByNewOrder(StreamingFPGrowth.java:615)
	at macrobase.analysis.summary.itemset.StreamingFPGrowth$StreamingFPTree.access$900(StreamingFPGrowth.java:36)
	at macrobase.analysis.summary.itemset.StreamingFPGrowth.restructureTree(StreamingFPGrowth.java:686)
	at macrobase.analysis.summary.itemset.StreamingFPGrowth.decayAndResetFrequentItems(StreamingFPGrowth.java:709)
	at macrobase.analysis.summary.itemset.ExponentiallyDecayingEmergingItemsets.updateModels(ExponentiallyDecayingEmergingItemsets.java:108)
	at macrobase.analysis.summary.itemset.ExponentiallyDecayingEmergingItemsets.updateModelsNoDecay(ExponentiallyDecayingEmergingItemsets.java:74)
	at macrobase.analysis.periodic.RetrainingProcedure.updatePeriod(RetrainingProcedure.java:29)
	at macrobase.analysis.periodic.TupleBasedRetrainer.updatePeriod(TupleBasedRetrainer.java:35)
	at macrobase.analysis.periodic.AbstractPeriodicUpdater.updateIfNecessary(AbstractPeriodicUpdater.java:12)
	at macrobase.analysis.StreamingAnalyzer.analyzeOnePass(StreamingAnalyzer.java:189)
	at macrobase.runtime.standalone.streaming.MacroBaseStreamingCommand.run(MacroBaseStreamingCommand.java:78)
	at macrobase.runtime.standalone.streaming.MacroBaseStreamingCommand.run(MacroBaseStreamingCommand.java:15)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:77)
	at io.dropwizard.cli.Cli.run(Cli.java:70)
	at io.dropwizard.Application.run(Application.java:80)
	at macrobase.runtime.MacroBaseServer.main(MacroBaseServer.java:26)
	at macrobase.MacroBase.main(MacroBase.java:38)
```

**Comment by pbailis** [comment]
Is this the same as #18?
