### ISSUE TITLE
Address already in use.

### ISSUE THREAD

**Issue by kemathur** [stanford-futuredata/macrobase#170]
I was recently introduced to MacroBase and wanted to give it a try. I have been following the [tutorial](https://github.com/stanford-futuredata/macrobase/wiki/Tutorial) and I had followed the steps but when I run bin/server.sh I get an exception:
```

INFO  [2016-10-29 07:09:45,783] io.dropwizard.server.DefaultServerFactory: Registering admin handler with root path prefix: /
INFO  [2016-10-29 07:09:45,837] org.eclipse.jetty.setuid.SetUIDListener: Opened application@435871cb{HTTP/1.1}{0.0.0.0:8080}
WARN  [2016-10-29 07:09:45,841] org.eclipse.jetty.util.component.AbstractLifeCycle: FAILED org.eclipse.jetty.server.Server@45cff11c: java.lang.RuntimeException: java.net.BindException: Address already in use
! java.net.BindException: Address already in use
! at sun.nio.ch.Net.bind0(Native Method) ~[na:1.8.0_111]
! at sun.nio.ch.Net.bind(Net.java:433) ~[na:1.8.0_111]
! at sun.nio.ch.Net.bind(Net.java:425) ~[na:1.8.0_111]
! at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223) ~[na:1.8.0_111]
! at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74) ~[na:1.8.0_111]
! at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:321) ~[macrobase-jar-with-dependencies.jar:na]
! at org.eclipse.jetty.setuid.SetUIDListener.lifeCycleStarting(SetUIDListener.java:200) ~[macrobase-jar-with-dependencies.jar:na]
! ... 8 common frames omitted
! Causing: java.lang.RuntimeException: java.net.BindException: Address already in use
! at org.eclipse.jetty.setuid.SetUIDListener.lifeCycleStarting(SetUIDListener.java:213) ~[macrobase-jar-with-dependencies.jar:na]
! at org.eclipse.jetty.util.component.AbstractLifeCycle.setStarting(AbstractLifeCycle.java:188) ~[macrobase-jar-with-dependencies.jar:na]
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:67) ~[macrobase-jar-with-dependencies.jar:na]
! at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:43) [macrobase-jar-with-dependencies.jar:na]
! at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:41) [macrobase-jar-with-dependencies.jar:na]
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:77) [macrobase-jar-with-dependencies.jar:na]
! at io.dropwizard.cli.Cli.run(Cli.java:70) [macrobase-jar-with-dependencies.jar:na]
! at io.dropwizard.Application.run(Application.java:80) [macrobase-jar-with-dependencies.jar:na]
! at macrobase.runtime.MacroBaseServer.main(MacroBaseServer.java:21) [classes/:na]
ERROR [2016-10-29 07:09:45,841] io.dropwizard.cli.ServerCommand: Unable to start server, shutting down
! java.net.BindException: Address already in use
! at sun.nio.ch.Net.bind0(Native Method) ~[na:1.8.0_111]
! at sun.nio.ch.Net.bind(Net.java:433) ~[na:1.8.0_111]
! at sun.nio.ch.Net.bind(Net.java:425) ~[na:1.8.0_111]
! at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223) ~[na:1.8.0_111]
! at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74) ~[na:1.8.0_111]
! at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:321) ~[macrobase-jar-with-dependencies.jar:na]
! at org.eclipse.jetty.setuid.SetUIDListener.lifeCycleStarting(SetUIDListener.java:200) ~[macrobase-jar-with-dependencies.jar:na]
! ... 8 common frames omitted
! Causing: java.lang.RuntimeException: java.net.BindException: Address already in use
! at org.eclipse.jetty.setuid.SetUIDListener.lifeCycleStarting(SetUIDListener.java:213) ~[macrobase-jar-with-dependencies.jar:na]
! at org.eclipse.jetty.util.component.AbstractLifeCycle.setStarting(AbstractLifeCycle.java:188) ~[macrobase-jar-with-dependencies.jar:na]
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:67) ~[macrobase-jar-with-dependencies.jar:na]
! at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:43) ~[macrobase-jar-with-dependencies.jar:na]
! at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:41) [macrobase-jar-with-dependencies.jar:na]
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:77) [macrobase-jar-with-dependencies.jar:na]
! at io.dropwizard.cli.Cli.run(Cli.java:70) [macrobase-jar-with-dependencies.jar:na]
! at io.dropwizard.Application.run(Application.java:80) [macrobase-jar-with-dependencies.jar:na]
! at macrobase.runtime.MacroBaseServer.main(MacroBaseServer.java:21) [classes/:na]
Exception in thread "main" java.lang.RuntimeException: java.net.BindException: Address already in use
	at org.eclipse.jetty.setuid.SetUIDListener.lifeCycleStarting(SetUIDListener.java:213)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.setStarting(AbstractLifeCycle.java:188)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:67)
	at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:43)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:41)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:77)
	at io.dropwizard.cli.Cli.run(Cli.java:70)
	at io.dropwizard.Application.run(Application.java:80)
	at macrobase.runtime.MacroBaseServer.main(MacroBaseServer.java:21)
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:321)
	at org.eclipse.jetty.setuid.SetUIDListener.lifeCycleStarting(SetUIDListener.java:200)
	... 8 more
```

When I try looking at localhost:8080 I don't see anything running. But localhost:8081 is being used by McAfee. I am not sure if that is the issue?

**Comment by pbailis** [comment]
Hi @kemathur,

You can change the server ports by editing `conf/macrobase.yaml`

```
server:
    applicationConnectors:
        - type: http
          port: 6666
    adminConnectors:
        - type: http
          port: 6667
```

I just pushed a fix to enable this; it's in the `shaded-jar` branch (https://github.com/stanford-futuredata/macrobase/tree/shaded-jar) and should be in `master` by the end of the week.

Please let me know if this doesn't work.

Thanks!
Peter

**Comment by kemathur** [comment]
Hello,

Sorry I was busy and could not get to it. I pulled the master again as I think shaded-jar is deleted. Now I get the following error:

```

  * Failed to parse configuration at: server.applicationConnectors.[0]; Could not resolve type id 'http' into a subtype of [simple type, class io.dropwizard.jetty.ConnectorFactory]: known type ids = [ConnectorFactory]
 at [Source: N/A; line: -1, column: -1] (through reference chain: macrobase.conf.MacroBaseConf["server"]->io.dropwizard.server.DefaultServerFactory["applicationConnectors"]->java.util.ArrayList[0])


```
