### ISSUE TITLE
NullPointerException in StreamingFPTree.sortByNewOrder()

### ISSUE THREAD

**Issue by deepakn94** [stanford-futuredata/macrobase#18]
Exception in thread "main" java.lang.NullPointerException
		at macrobase.analysis.summary.itemset.StreamingFPGrowth$StreamingFPTree.sortByNewOrder(StreamingFPGrowth.java:615)
		at macrobase.analysis.summary.itemset.StreamingFPGrowth$StreamingFPTree.access$900(StreamingFPGrowth.java:36)
		at macrobase.analysis.summary.itemset.StreamingFPGrowth.restructureTree(StreamingFPGrowth.java:686)
		at macrobase.analysis.summary.itemset.StreamingFPGrowth.decayAndResetFrequentItems(StreamingFPGrowth.java:709)
		at macrobase.analysis.summary.itemset.ExponentiallyDecayingEmergingItemsets.updateModels(ExponentiallyDecayingEmergingItemsets.java:108)
		at macrobase.analysis.summary.itemset.ExponentiallyDecayingEmergingItemsets.updateModelsNoDecay(ExponentiallyDecayingEmergingItemsets.java:74)
		at macrobase.analysis.periodic.RetrainingProcedure.updatePeriod(RetrainingProcedure.java:29)
		at macrobase.analysis.periodic.TupleBasedRetrainer.updatePeriod(TupleBasedRetrainer.java:35)
		at macrobase.analysis.periodic.AbstractPeriodicUpdater.updateIfNecessary(AbstractPeriodicUpdater.java:12)
		at macrobase.analysis.StreamingAnalyzer.analyzeOnePass(StreamingAnalyzer.java:189)
		at macrobase.runtime.standalone.streaming.MacroBaseStreamingCommand.run(MacroBaseStreamingCommand.java:78)
		at macrobase.runtime.standalone.streaming.MacroBaseStreamingCommand.run(MacroBaseStreamingCommand.java:15)
		at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:77)
		at io.dropwizard.cli.Cli.run(Cli.java:70)
		at io.dropwizard.Application.run(Application.java:80)
		at macrobase.runtime.MacroBaseServer.main(MacroBaseServer.java:26)
		at macrobase.MacroBase.main(MacroBase.java:38)

This is on the `cmtDatasetComplexStreaming` workload. (same version that is on `origin/master`)

**Comment by pbailis** [comment]
There was a bug that caused NPEs in two parts of the code.

### The Basic Problem

When we delete a node (because its corresponding item is no longer supported), we need to attach its children to the node's parent. For example, if we delete item 10 that has a corresponding node N, we need to delete N and then merge N.children into N.parent.

There is a branch in the implementation of `mergeChildren` that handles the case where `parent.children == null`. If N.parent has no children, so we can just set N.parent.children = N.children. 

However, when we reassign N.parent.children to N.children, we *also* need to update the parent pointer for each child in N.children to point to N.parent. Otherwise the nodes in N.children will point to a node that has been deleted (N).

In [my implementation](https://github.com/stanford-futuredata/macrobase/blob/aa7d3a181c913ec8441c8a314d3650a47db37476/src/main/java/macrobase/analysis/summary/itemset/StreamingFPGrowth.java#L162), I forgot to reassign the children's parent pointers. So the N.parent pointed to the children, but the children still pointed to N.

### The effects (the NPEs)

There were two separate NPEs as a result:

 1. When we delete a node N' because it's no longer frequent and N' was a leaf node of the tree, we need up update our mapping of leaf nodes. Specifically, we want to mark the parent of N' as a leaf node. However, because the parent pointers weren't being updated, we were adding previously deleted nodes to the set of leaf nodes ([`leafNodes`](https://github.com/stanford-futuredata/macrobase/blob/aa7d3a181c913ec8441c8a314d3650a47db37476/src/main/java/macrobase/analysis/summary/itemset/StreamingFPGrowth.java#L338)). This triggered the above NPE at [L615](https://github.com/stanford-futuredata/macrobase/blob/aa7d3a181c913ec8441c8a314d3650a47db37476/src/main/java/macrobase/analysis/summary/itemset/StreamingFPGrowth.java#L615).

 2. When we strip out a tree path for re-insertion in sorted order, we traverse the tree from leaf to root. Given the above bug, if our deleted node N lay in the path from a leaf to the root, we would access it and attempt to read its location in the sorted node order, resulting in an NPE on  [L615](https://github.com/stanford-futuredata/macrobase/blob/aa7d3a181c913ec8441c8a314d3650a47db37476/src/main/java/macrobase/analysis/summary/itemset/StreamingFPGrowth.java#L615).

Pretty ugly, but a three-line fix (one line if you have a one-line `for` loop.

**Comment by deepakn94** [comment]
Nice catch.
