### ISSUE TITLE
IndexOutofBoundsException

### ISSUE THREAD

**Issue by deepakn94** [stanford-futuredata/macrobase#26]
Exception in thread "main" java.lang.IndexOutOfBoundsException: toIndex = 1008
	        at java.util.ArrayList.subListRangeCheck(ArrayList.java:1004)
	        at java.util.ArrayList.subList(ArrayList.java:996)
	        at macrobase.analysis.outlier.MinCovDet.findKClosest(MinCovDet.java:169)
	        at macrobase.analysis.outlier.MinCovDet.train(MinCovDet.java:217)
	        at macrobase.analysis.StreamingAnalyzer.analyzeOnePass(StreamingAnalyzer.java:183)
	        at macrobase.runtime.standalone.streaming.MacroBaseStreamingCommand.run(MacroBaseStreamingCommand.java:81)
	        at macrobase.runtime.standalone.streaming.MacroBaseStreamingCommand.run(MacroBaseStreamingCommand.java:15)
	        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:77)
	        at io.dropwizard.cli.Cli.run(Cli.java:70)
	        at io.dropwizard.Application.run(Application.java:80)
	        at macrobase.runtime.MacroBaseServer.main(MacroBaseServer.java:26)
	        at macrobase.MacroBase.main(MacroBase.java:38)
	Exception in thread "main" java.lang.IndexOutOfBoundsException: toIndex = 1004
	        at java.util.ArrayList.subListRangeCheck(ArrayList.java:1004)
	        at java.util.ArrayList.subList(ArrayList.java:996)
	        at macrobase.analysis.outlier.MinCovDet.findKClosest(MinCovDet.java:169)
	        at macrobase.analysis.outlier.MinCovDet.train(MinCovDet.java:217)
	        at macrobase.analysis.StreamingAnalyzer.analyzeOnePass(StreamingAnalyzer.java:183)
	        at macrobase.runtime.standalone.streaming.MacroBaseStreamingCommand.run(MacroBaseStreamingCommand.java:81)
	        at macrobase.runtime.standalone.streaming.MacroBaseStreamingCommand.run(MacroBaseStreamingCommand.java:15)
	        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:77)
	        at io.dropwizard.cli.Cli.run(Cli.java:70)
	        at io.dropwizard.Application.run(Application.java:80)
	        at macrobase.runtime.MacroBaseServer.main(MacroBaseServer.java:26)
	        at macrobase.MacroBase.main(MacroBase.java:38)
	Exception in thread "main" java.lang.IndexOutOfBoundsException: toIndex = 1007
	        at java.util.ArrayList.subListRangeCheck(ArrayList.java:1004)
	        at java.util.ArrayList.subList(ArrayList.java:996)
	        at macrobase.analysis.outlier.MinCovDet.findKClosest(MinCovDet.java:169)
	        at macrobase.analysis.outlier.MinCovDet.train(MinCovDet.java:217)
	        at macrobase.analysis.StreamingAnalyzer.analyzeOnePass(StreamingAnalyzer.java:183)
	        at macrobase.runtime.standalone.streaming.MacroBaseStreamingCommand.run(MacroBaseStreamingCommand.java:81)
	        at macrobase.runtime.standalone.streaming.MacroBaseStreamingCommand.run(MacroBaseStreamingCommand.java:15)
	        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:77)
	        at io.dropwizard.cli.Cli.run(Cli.java:70)
	        at io.dropwizard.Application.run(Application.java:80)
	        at macrobase.runtime.MacroBaseServer.main(MacroBaseServer.java:26)
	        at macrobase.MacroBase.main(MacroBase.java:38)

On cmtDatasetSimple, alphaMCD = 1.0

**Comment by pbailis** [comment]
H = alpha*(n+p+1), so alpha = 1.0 is bad news. Going to fix this in two commits -- one to fix the bounds, one to switch to a priority queue.
